version: '3'
services:
  server:
    build: ./server
    ports:
      - '5000:5000'

  client:
    build:
      context: ./client
      args:
        - BACKEND_URL=http://localhost:5000
    ports:
      - '3000:3000'
